bundler:
  rails:
    - 5.2
    - 6.0
    - 6.1
composer:
  laravel:
    - 6
    - 8
  drupal/core:
    - 9.2
    - 9.1
  magento/community-edition:
    - 2.4
  symfony:
    - 5.3
    - 4.4
    - 3.4
npm:
  bootstrap:
    - 4
    - 5
maven:
  spring:
    - 5.2
    - 5.3
pip:
  django:
    - 3.2
    - 3.1
    - 2.2
  wagtail:
    - 2.13
    - 2.12
    - 2.11
